version: "1.0"
dataset: "creditcard"
random_seed: 42

imbalance_ratios: [1.0, 0.5, 0.1]

model: "mlp-64"
num_layers: [2]
hidden_size: 64
epochs: 50
batch_size: 1024
test_size: 0.2
val_size: 0.1
lr: 0.001

losses: ["ce", "wce", "focal"]
focal_alpha: [0.25]
focal_gamma: [2.0, 5.0]
ce_weights: [5, 10, 577]