version: "1.0"
dataset: "creditcard"
random_seed: 42

#imbalance_ratios: [0.01, 0.25, 0.5]
#imbalance_ratios: [0.5, 0.25, 0.01]
imbalance_ratios: [1.0, 0.5, 0.1]
model: "mlp-64"
#num_layers: [2, 4]
num_layers: [2]
hidden_size: 64
epochs: 50
batch_size: 1024
test_size: 0.2
val_size: 0.1
lr: 0.001
losses: ["ce", "wce", "focal"]
#focal_alpha: [0.1, 0.25, 0.5, 0.75, 0.9, 0.95] # Focusing between balanced 0.5 and hard imbalance 0.95
focal_alpha: [0.25]
#focal_gamma: [0.0, 0.5, 1.0, 2.0, 5.0]
focal_gamma: [2.0, 5.0]
# TODO: Adaptive weight based on imbalance ratio
#ce_weights: [1.0, 5.0, 10.0, 25.0, 50.0, 90.0, 100.0]
ce_weights: [5, 10, 577]

# TODO: Inspect batches if they contain only few minority samples
# TODO: Inspect if values being plotted correctly
# TODO: Run experiment with:
#num_layers: [2, 4]
#focal_alpha: [0.25, 0.5 0.9]
#focal_gamma: [2.0, 5.0]
#ce_weights: [10.0, 50.0, 100.0, 577.88]