version: "1.0"
mlflow_port: "32769"
mlflow_experiment_name: "Plot_Test_Medium_CE"

random_seed: 42

# Dataset
creditcard_csv: "creditcard.csv"
test_size: 0.2
val_size: 0.1
batch_size: 256
imbalance_ratios: [1.0, 0.6, 0.3, 0.0]

# Training
epochs: 20
lr: 0.001

# Models
models: ["medium"]

# Loss sweep parameters
#losses: ["ce", "wce", "focal"]
losses: ["ce", "wce", "focal"]
#focal_gamma: [0.0, 1.0, 2.0, 5.0]
focal_gamma: [2.0, 5.0]
